{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "next-service.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data: {{- toYaml .data | nindent 4 }}
{{- end }}
