// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

// One edge in the social graph.
type FollowEdge struct {
	UserID     string    `json:"userId"`
	Handle     string    `json:"handle"`
	FollowedAt time.Time `json:"followedAt"`
}

type FollowInput struct {
	FollowerID string `json:"followerId"`
	FolloweeID string `json:"followeeId"`
}

type FollowersConnection struct {
	Edges      []*FollowEdge `json:"edges"`
	NextCursor *string       `json:"nextCursor,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// RegisterUserInput drives auth-service.RegisterUser. The matching profile
// is materialized asynchronously by profile-service via the
// auth.user.registered.v1 Kafka event.
type RegisterUserInput struct {
	Handle      string  `json:"handle"`
	DisplayName *string `json:"displayName,omitempty"`
}

type RegisterUserResult struct {
	User *User `json:"user"`
}

// A NEXT user. id is the canonical ID owned by auth-service.
// Handle, displayName, bio, follower counts come from profile-service.
type User struct {
	ID          string    `json:"id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"displayName"`
	Bio         string    `json:"bio"`
	Tier        Tier      `json:"tier"`
	Followers   int       `json:"followers"`
	Following   int       `json:"following"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// The user's tier — defines what scopes they can use and what surfaces they see.
type Tier string

const (
	TierAuthenticated Tier = "AUTHENTICATED"
	TierCreator       Tier = "CREATOR"
	TierPartner       Tier = "PARTNER"
	TierStaff         Tier = "STAFF"
)

var AllTier = []Tier{
	TierAuthenticated,
	TierCreator,
	TierPartner,
	TierStaff,
}

func (e Tier) IsValid() bool {
	switch e {
	case TierAuthenticated, TierCreator, TierPartner, TierStaff:
		return true
	}
	return false
}

func (e Tier) String() string {
	return string(e)
}

func (e *Tier) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Tier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Tier", str)
	}
	return nil
}

func (e Tier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
