package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"time"

	authv1 "github.com/next-ecosystem/next/gen/go/auth/v1"
	profilev1 "github.com/next-ecosystem/next/gen/go/profile/v1"
	"github.com/next-ecosystem/next/services/api-gateway/internal/authz"
	"github.com/next-ecosystem/next/services/api-gateway/internal/gql/generated"
	"github.com/next-ecosystem/next/services/api-gateway/internal/gql/model"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.RegisterUserInput) (*model.RegisterUserResult, error) {
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	authResp, err := r.AuthUsers.RegisterUser(ctx, &authv1.RegisterUserRequest{
		Handle:      input.Handle,
		DisplayName: derefString(input.DisplayName),
	})
	if err != nil {
		return nil, translateGRPCError(err)
	}

	profile, _ := r.tryFetchProfile(ctx, authResp.GetUserId(), 1*time.Second)
	if profile == nil {
		profile = &model.User{
			ID:          authResp.GetUserId(),
			Handle:      input.Handle,
			DisplayName: derefString(input.DisplayName),
			Tier:        model.TierAuthenticated,
			Followers:   0,
			Following:   0,
			CreatedAt:   time.Now().UTC(),
			UpdatedAt:   time.Now().UTC(),
		}
	}
	return &model.RegisterUserResult{User: profile}, nil
}

// Follow is the resolver for the follow field.
func (r *mutationResolver) Follow(ctx context.Context, input model.FollowInput) (bool, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	if _, err := r.SocialGraph.Follow(ctx, &profilev1.FollowRequest{
		FollowerId: input.FollowerID,
		FolloweeId: input.FolloweeID,
	}); err != nil {
		return false, translateGRPCError(err)
	}
	return true, nil
}

// Unfollow is the resolver for the unfollow field.
func (r *mutationResolver) Unfollow(ctx context.Context, input model.FollowInput) (bool, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	if _, err := r.SocialGraph.Unfollow(ctx, &profilev1.UnfollowRequest{
		FollowerId: input.FollowerID,
		FolloweeId: input.FolloweeID,
	}); err != nil {
		return false, translateGRPCError(err)
	}
	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	claims := authz.ClaimsFromContext(ctx)
	if claims == nil || claims.Subject == "" {
		return nil, nil
	}
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	return r.tryFetchProfile(ctx, claims.Subject, 0)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	return r.tryFetchProfile(ctx, id, 0)
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string, first *int, after *string) (*model.FollowersConnection, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	resp, err := r.SocialGraph.Followers(ctx, &profilev1.FollowersRequest{
		UserId: userID,
		Limit:  derefInt32(first, 25),
		After:  derefString(after),
	})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return toFollowersConnection(resp.GetEdges(), resp.GetNextCursor()), nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string, first *int, after *string) (*model.FollowersConnection, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	resp, err := r.SocialGraph.Following(ctx, &profilev1.FollowingRequest{
		UserId: userID,
		Limit:  derefInt32(first, 25),
		After:  derefString(after),
	})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return toFollowersConnection(resp.GetEdges(), resp.GetNextCursor()), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
